### ISSUE TITLE
Pop without accolades?

### ISSUE THREAD

**Issue by Heretic6667** [Darkdoom22/AutoUNM#3]
Addon has allowed me to pop UNMs without having the required amount of accolades.  It doesn't give a reward upon defeat, but vanilla behavior is to prevent you from popping.  Is this intended behavior?

**Comment by Darkdoom22** [comment]
Added this a while ago and forgot to push to git, just pushed.  Bot will stop if you have less than 3100 accolades now (there's no simple way to check the cost of the UNM you're intending to pop so I went with the acc cost of the i145 UNMs, you can lower to match the one you're farming if you desire, line 170).  Your other issue is because it blocks the menu so that it can handle the interaction itself, I'll look into adding a check so it doesn't block the menu if you click it accidentally (or just a way to release yourself if you get stuck) soon. @Tathamet667
